
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed May 28 15:48:57 BRT 2014
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MULT = 29;
  public static final int DIFERENTE = 34;
  public static final int ATR = 24;
  public static final int INT = 11;
  public static final int VIRGULA = 23;
  public static final int WRITE = 16;
  public static final int IDENTIFICADOR = 18;
  public static final int LIT_INTEIRO = 19;
  public static final int NOT = 6;
  public static final int AND = 4;
  public static final int IGUAL = 33;
  public static final int OR = 5;
  public static final int MAIS = 27;
  public static final int BEGIN = 2;
  public static final int IF = 7;
  public static final int A_PARENTESE = 25;
  public static final int WRITELN = 17;
  public static final int EOF = 0;
  public static final int BOOLEAN = 14;
  public static final int MAIOR = 36;
  public static final int PONTO_VIRGULA = 22;
  public static final int error = 1;
  public static final int LIT_STRING = 21;
  public static final int MENOS = 28;
  public static final int MENOR = 31;
  public static final int LIT_BOOLEANO = 20;
  public static final int F_PARENTESE = 26;
  public static final int READLN = 15;
  public static final int DIVI = 30;
  public static final int BYTE = 12;
  public static final int ELSE = 8;
  public static final int FINAL = 10;
  public static final int WHILE = 9;
  public static final int END = 3;
  public static final int STRING = 13;
  public static final int MENOR_IGUAL = 32;
  public static final int MAIOR_IGUAL = 35;
}

